// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkafzarnschmdbxevicb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrYWZ6YXJuc2NobWRieGV2aWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3Njc0MTcsImV4cCI6MjA1NTM0MzQxN30.-anwBXJ_B9tfTl0PqtUt_YtmrA07MuHawP65CTVBb5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});